name: PR Quality & Security

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  codeql-scan:
    name: Code scanning (CodeQL)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild (if needed)
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  pr-quality:
    name: Lint & Tests
    runs-on: ubuntu-latest
    needs: codeql-scan
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm run test --if-present

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-artifacts
          path: |
            npm-debug.log
            test-results-*.xml
            coverage
