name: PR Quality & Security

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  codeql-scan:
    name: CodeQL Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild (if needed)
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

  pr-quality:
    name: Lint → Test → Artifact Upload
    runs-on: ubuntu-latest
    needs: codeql-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (if configured)
        run: |
          if jq -e '.scripts.lint' package.json >/dev/null 2>&1; then
            npm run lint
          else
            echo "No lint script found; skipping."
          fi

      - name: Run tests (if configured)
        run: |
          if jq -e '.scripts.test' package.json >/dev/null 2>&1; then
            npm test --silent
          else
            echo "No test script found; skipping."
          fi

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-artifacts
          path: |
            coverage
            npm-debug.log
            test-results*.xml
