name: Dependency PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  dependency-tests:
    name: Verify Dependency Updates
    runs-on: ubuntu-latest

    # Only run if PR is from Dependabot or has "dependencies" label
    if: >
      contains(github.event.pull_request.user.login, 'dependabot[bot]') ||
      contains(join(github.event.pull_request.labels.*.name, ','), 'dependencies')

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Run lint checks (if defined)
      - name: Run lint
        run: |
          if jq -e '.scripts.lint' package.json >/dev/null 2>&1; then
            npm run lint
          else
            echo "No lint script found; skipping."
          fi

      # Run tests (if defined)
      - name: Run tests
        run: |
          if jq -e '.scripts.test' package.json >/dev/null 2>&1; then
            npm test --silent
          else
            echo "No test script found; skipping."
          fi

      # Upload logs or test artifacts for debugging
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-test-artifacts
          path: |
            npm-debug.log
            coverage
            test-results
