name: Scheduled maintenance / scrape

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (persist credentials for push)
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run scheduled script (run.js)
        run: |
          if [ -f ./run.js ]; then
            node run.js
          else
            echo "No run.js to execute."
          fi

      - name: Show modified files
        run: git status --porcelain || true

      - name: Commit and push generated changes (if any)
        env:
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: scheduled update (automated)"
            git push origin HEAD:main
          fi
